# Generated by Django 5.0.10 on 2025-01-17 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMst',
            fields=[
                ('userid', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('umei', models.CharField(blank=True, max_length=40, null=True, verbose_name='氏名')),
                ('approval_id', models.IntegerField(blank=True, null=True, verbose_name='承認者')),
                ('apmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='承認者氏名')),
                ('ap_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='承認者email')),
                ('last_approval_id', models.IntegerField(blank=True, null=True, verbose_name='最終承認者')),
                ('lsmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='最終承認者氏名')),
                ('last_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='最終承認email')),
            ],
            options={
                'verbose_name_plural': '承認者マスタ',
                'db_table': 'ApprovalMst',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='部署名')),
            ],
            options={
                'verbose_name_plural': '部署マスタ',
                'db_table': 'DepartmentMst',
            },
        ),
        migrations.CreateModel(
            name='OffdayKbnMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbnmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='勤怠区分')),
            ],
            options={
                'verbose_name_plural': '勤怠区分マスタ',
                'db_table': 'OffdayKbnMst',
            },
        ),
        migrations.CreateModel(
            name='PeriodMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=40, null=True, verbose_name='期間')),
            ],
            options={
                'verbose_name_plural': '期間マスタ',
                'db_table': 'PeriodMst',
            },
        ),
        migrations.CreateModel(
            name='RequestMst',
            fields=[
                ('requestID', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='requestID')),
                ('RequestType', models.CharField(blank=True, max_length=255, null=True, verbose_name='RequestType')),
                ('needMeeting', models.BooleanField(default=False)),
                ('needRingi', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '申請マスタ',
                'db_table': 'RequestMst',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='従業員名')),
                ('d_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.departmentmst')),
            ],
            options={
                'verbose_name_plural': '従業員マスタ',
                'db_table': 'EmployeeMst',
            },
        ),
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, null=True)),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('if_account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '案内データ',
                'db_table': 'InfoData',
            },
        ),
        migrations.CreateModel(
            name='OffdayRequestMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='従業員名')),
                ('u_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='勤怠申請者')),
            ],
            options={
                'verbose_name_plural': '勤怠申請対象者マスタ',
                'db_table': 'OffdayRequestMst',
            },
        ),
        migrations.CreateModel(
            name='OffDayData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('offday_date', models.DateField(verbose_name='日時')),
                ('content', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='理由')),
                ('approval_id', models.IntegerField(blank=True, null=True)),
                ('apmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ap_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='承認')),
                ('approval_read', models.BooleanField(default=False)),
                ('last_approval_id', models.IntegerField(blank=True, null=True)),
                ('lsmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ls_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('last_approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='最終承認')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('end_offday_date', models.DateField(blank=True, null=True, verbose_name='日時(至)')),
                ('od_account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offday_kbn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.offdaykbnmst', verbose_name='勤怠区分')),
                ('emp_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.offdayrequestmst', verbose_name='従業員')),
                ('period_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.periodmst', verbose_name='期間')),
            ],
            options={
                'verbose_name_plural': '勤怠申請データ',
                'db_table': 'OffDayData',
            },
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('approval_id', models.IntegerField(blank=True, null=True)),
                ('apmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ap_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='承認')),
                ('approval_read', models.BooleanField(default=False)),
                ('last_approval_id', models.IntegerField(blank=True, null=True)),
                ('lsmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ls_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('last_approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='最終承認')),
                ('last_read', models.BooleanField(default=False)),
                ('withdrawal', models.BooleanField(default=False)),
                ('withdrawal_id', models.IntegerField(blank=True, null=True, verbose_name='最終承認者')),
                ('rq_account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_folder.requestmst', verbose_name='申請項目')),
            ],
            options={
                'verbose_name_plural': '申請データ',
                'db_table': 'RequestData',
            },
        ),
    ]
