# Generated by Django 5.0.10 on 2025-01-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmst',
            name='approval_id',
            field=models.IntegerField(blank=True, choices=[(1, '坂下恭之'), (2, 'テスト１')], null=True, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='approvalmst',
            name='last_approval_id',
            field=models.IntegerField(blank=True, choices=[(1, '坂下恭之'), (2, 'テスト１')], null=True, verbose_name='最終承認者'),
        ),
    ]
