# Generated by Django 5.0.10 on 2025-01-17 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_alter_approvalmst_approval_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffDayData2',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('offday_date', models.DateField(verbose_name='日時')),
                ('content', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='理由')),
                ('approval_id', models.IntegerField(blank=True, null=True)),
                ('apmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ap_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='承認')),
                ('approval_read', models.BooleanField(default=False)),
                ('last_approval_id', models.IntegerField(blank=True, null=True)),
                ('lsmei', models.CharField(blank=True, max_length=40, null=True)),
                ('ls_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_approval_content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('last_approval', models.IntegerField(choices=[(0, '未承認'), (1, '承認済'), (2, '却下')], default=0, verbose_name='最終承認')),
                ('end_offday_date', models.DateField(blank=True, null=True, verbose_name='日時(至)')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('emp_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.offdayrequestmst', verbose_name='従業員')),
                ('od_account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offday_kbn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.offdaykbnmst', verbose_name='勤怠区分')),
                ('period_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.periodmst', verbose_name='期間')),
            ],
            options={
                'verbose_name_plural': '勤怠申請データ',
                'db_table': 'OffDayData2',
            },
        ),
    ]
