# Generated by Django 5.0.10 on 2025-01-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_offdaydata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffDayData2',
        ),
    ]
