# Generated by Django 5.0.10 on 2025-01-20 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_delete_offdaydata2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoConfirm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('if_account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('if_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.infodata')),
            ],
            options={
                'verbose_name_plural': '案内確認',
                'db_table': 'InfoConfirm',
            },
        ),
    ]
