# Generated by Django 5.0.10 on 2025-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0005_infoconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodata',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
