# Generated by Django 5.0.10 on 2025-01-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_infodata_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoconfirm',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
