# Generated by Django 5.0.10 on 2025-01-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_alter_infoconfirm_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSelectMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermei', models.CharField(blank=True, max_length=40, null=True)),
                ('account_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_folder.requestmst', verbose_name='申請項目')),
            ],
            options={
                'verbose_name_plural': '申請選択マスタ',
                'db_table': 'RequestSelectMst',
            },
        ),
    ]
