# Generated by Django 5.0.10 on 2025-01-23 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0008_requestselectmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqMst',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_no', models.IntegerField(default=0, verbose_name='申請承認番号')),
                ('offday_ap_no', models.IntegerField(default=0, verbose_name='勤怠承認番号')),
            ],
            options={
                'verbose_name_plural': 'シーケンスマスタ',
                'db_table': 'SeqMst',
            },
        ),
        migrations.AddField(
            model_name='offdaydata',
            name='ap_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offdaydata',
            name='attach2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='offdaydata',
            name='attach3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='ap_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='attach2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='attach3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.DeleteModel(
            name='RequestSelectMst',
        ),
    ]
