# Generated by Django 5.0.10 on 2025-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0010_settingmst'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='chkJimu',
            field=models.BooleanField(default=False, verbose_name='要事務所確認'),
        ),
        migrations.AddField(
            model_name='requestmst',
            name='chkJimu',
            field=models.BooleanField(default=False, verbose_name='要事務所確認'),
        ),
        migrations.AlterField(
            model_name='requestmst',
            name='RequestType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='申請項目名'),
        ),
        migrations.AlterField(
            model_name='requestmst',
            name='needMeeting',
            field=models.BooleanField(default=False, verbose_name='要会議招集'),
        ),
        migrations.AlterField(
            model_name='requestmst',
            name='needRingi',
            field=models.BooleanField(default=False, verbose_name='要稟議書'),
        ),
        migrations.AlterField(
            model_name='requestmst',
            name='requestID',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='項目ID'),
        ),
    ]
