# Generated by Django 5.0.10 on 2025-02-03 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0011_requestdata_chkjimu_requestmst_chkjimu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImproveKbnMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbnmei', models.CharField(blank=True, max_length=40, null=True, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name_plural': '改善提案区分マスタ',
                'db_table': 'ImproveKbnMst',
            },
        ),
        migrations.AddField(
            model_name='employeemst',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settingmst',
            name='send_pass',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='employeemst',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.departmentmst'),
        ),
        migrations.CreateModel(
            name='ImprovementData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_mei', models.CharField(blank=True, max_length=40, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ReqDate', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ttl', models.CharField(blank=True, max_length=40, null=True, verbose_name='題名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('answer_id', models.IntegerField(blank=True, null=True)),
                ('answer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('Importance', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='重要度')),
                ('priority', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='優先度')),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('imp_no', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.employeemst')),
                ('kbn_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.improvekbnmst', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name_plural': '改善提案データ',
                'db_table': 'ImprovementData',
            },
        ),
    ]
