# Generated by Django 5.0.10 on 2025-02-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0012_improvekbnmst_employeemst_email_settingmst_send_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementdata',
            name='ans_mei',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='emp_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.employeemst', verbose_name='氏名'),
        ),
    ]
