# Generated by Django 5.0.10 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0013_improvementdata_ans_mei_alter_improvementdata_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqmst',
            name='imp_no',
            field=models.IntegerField(default=0, verbose_name='改善提案番号'),
        ),
        migrations.AddField(
            model_name='settingmst',
            name='imp_str',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='改善提案附番'),
        ),
        migrations.AlterField(
            model_name='settingmst',
            name='ap_str',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='申請承認附番'),
        ),
        migrations.AlterField(
            model_name='settingmst',
            name='od_str',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='勤怠承認附番'),
        ),
        migrations.AlterField(
            model_name='settingmst',
            name='send_pass',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='改善提案パスワード'),
        ),
    ]
