# Generated by Django 5.0.10 on 2025-02-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0015_alter_improvementdata_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementdata',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='ttl',
            field=models.CharField(max_length=40, null=True, verbose_name='題名'),
        ),
    ]
