# Generated by Django 5.0.10 on 2025-02-07 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0016_alter_improvementdata_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmst',
            name='opinion_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='意見箱宛先'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='Importance',
            field=models.IntegerField(choices=[(0, '\u3000'), (1, '低'), (2, '中'), (3, '高')], default=0, verbose_name='重要度'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_folder.employeemst', verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='kbn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_folder.improvekbnmst', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='priority',
            field=models.IntegerField(choices=[(0, '\u3000'), (1, '低'), (2, '中'), (3, '高')], default=0, verbose_name='優先度'),
        ),
    ]
