# Generated by Django 5.0.10 on 2025-02-12 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0017_settingmst_opinion_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='employeemst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='improvekbnmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='offdaydata',
            name='emp_mei',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='offdaykbnmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='offdayrequestmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='periodmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='requestmst',
            name='del_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='employeemst',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.departmentmst'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.employeemst', verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='improvementdata',
            name='kbn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.improvekbnmst', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='infoconfirm',
            name='if_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offdaydata',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.offdayrequestmst', verbose_name='従業員'),
        ),
        migrations.AlterField(
            model_name='offdaydata',
            name='od_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offdaydata',
            name='offday_kbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.offdaykbnmst', verbose_name='勤怠区分'),
        ),
        migrations.AlterField(
            model_name='offdaydata',
            name='period_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.periodmst', verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='offdayrequestmst',
            name='u_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='勤怠申請者'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='requestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_folder.requestmst', verbose_name='申請項目'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='rq_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
