# Generated by Django 5.0.10 on 2025-02-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0018_approvalmst_del_flg_employeemst_del_flg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodata',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='全従業員閲覧可'),
        ),
    ]
