# Generated by Django 5.0.10 on 2025-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0019_infodata_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodata',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='画像添付'),
        ),
    ]
